### ISSUE TITLE
Staffs

### ISSUE THREAD

**Issue by hwalnest** [poketwo/forms.poketwo.net#1]
Staffs SHOULD NOT HAVE THERE DMS CLOSE I was muted for alt check and told to dm a staff but all of them have there dms closed 

I'm HawksNest#0474 and I'm the alt of XFinity#8462

**Comment by Anoeaa** [comment]
Not all staff have their DMs closed. Mine are for example always open. search for me and message me when you are on Discord!

**Comment by hwalnest** [comment]
oki

**Comment by hwalnest** [comment]
> Not all staff have their DMs closed. Mine are for example always open. search for me and message me when you are on Discord!

i pinged u in gen with my main
